### ISSUE TITLE
Add target SDK 30

### ISSUE THREAD

**Issue by stephannielsen** [mreichelt/docker-android#21]
Target SDK 30 is out :)

**Comment by mreichelt** [comment]
Hey @stephannielsen - thank you so much for your contribution! 👏  🎉 

I'm sorry it took so long, but I'm building and pushing the new images from my local machine at the very moment. The new images should pop up on [Docker Hub](https://hub.docker.com/r/mreichelt/android) in a few hours.

**Comment by mreichelt** [comment]
Again, thanks for your help @stephannielsen. The images `latest`, `30` and `30-system` are now live! I had to install a Google Play system image on `30-system` because the `default` ones are gone, but apart from that everything should work fine!
