### ISSUE TITLE
Add recipe for CircleCI

### ISSUE THREAD

**Issue by mreichelt** [mreichelt/docker-android#7]
Add a minimal recipe of how to build an Android app (target 28) on CircleCI, similar to [.gitlab-ci.yml](https://github.com/mreichelt/docker-android/blob/master/recipes/gitlab-ci/.gitlab-ci.yml), and add it to the [recipes](https://github.com/mreichelt/docker-android/tree/master/recipes) folder.

**Comment by NemoOudeis** [comment]
I posed this question in the PR but let me reiterate here: what is the advantage of these images over [circleci/android](https://hub.docker.com/r/circleci/android/) images (src [here](https://github.com/circleci/circleci-images/tree/staging/android)) (or anything other android images)?
