### ISSUE TITLE
Add recipe for TravisCI

### ISSUE THREAD

**Issue by mreichelt** [mreichelt/docker-android#8]
Add a minimal recipe of how to build an Android app (target 28) on TravisCI, similar to [.gitlab-ci.yml](https://github.com/mreichelt/docker-android/blob/master/recipes/gitlab-ci/.gitlab-ci.yml), and add it to the [recipes](https://github.com/mreichelt/docker-android/tree/master/recipes) folder.

**Comment by ghost** [comment]
Travis doesn't seem to support docker images so would it be fine if a default android image was used?

**Comment by ghost** [comment]
My bad didn't think about building an image with services!

**Comment by mreichelt** [comment]
That's the question - reading https://docs.travis-ci.com/user/docker/ I think it should be possible 😃

**Comment by ghost** [comment]
I added a pull request, hopefully this is ok!
